//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportSY.Data.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestStatuses
    {
        public System.Guid RequestID { get; set; }
        public int RequsetStatusID { get; set; }
    
        public virtual RequestStatusTypes RequestStatusTypes { get; set; }
        public virtual RequestStatusTypes RequestStatusTypes1 { get; set; }
        public virtual Rquest Rquest { get; set; }
    }
}
